# Generated by Django 3.2.5 on 2021-09-04 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_post_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user',
        ),
    ]
