# Generated by Django 3.2.5 on 2021-08-05 08:05

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('display_image', models.ImageField(null=True, upload_to='displayimg/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
