# Generated by Django 3.2.5 on 2021-08-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_user_isverified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
