# Generated by Django 3.2.5 on 2021-09-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_userrelationsip'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrelationsip',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='userrelationsip',
            constraint=models.UniqueConstraint(fields=('user_id', 'following_user_id'), name='unique_followers'),
        ),
    ]
