# Generated by Django 3.2.5 on 2021-09-01 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20210901_1731'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRelationsip',
            new_name='UserRelationship',
        ),
    ]
