# Generated by Django 3.2.5 on 2021-09-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_rename_userrelationsip_userrelationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_image',
            field=models.ImageField(default='displayimg/defaultavatar.png', null=True, upload_to='displayimg/'),
        ),
    ]
