# Generated by Django 3.2.5 on 2021-09-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_alter_user_display_image'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userrelationship',
            name='unique_followers',
        ),
        migrations.RenameField(
            model_name='userrelationship',
            old_name='following_user_id',
            new_name='following_user',
        ),
        migrations.RenameField(
            model_name='userrelationship',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='display_image',
            field=models.ImageField(null=True, upload_to='displayimg/'),
        ),
        migrations.AddConstraint(
            model_name='userrelationship',
            constraint=models.UniqueConstraint(fields=('user', 'following_user'), name='unique_followers'),
        ),
    ]
